# Generated by Django 4.0 on 2022-10-17 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_order'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='email',
            new_name='Email',
        ),
        migrations.RemoveField(
            model_name='order',
            name='accepted',
        ),
        migrations.RemoveField(
            model_name='order',
            name='details',
        ),
        migrations.AddField(
            model_name='order',
            name='name',
            field=models.CharField(default=1, max_length=1000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='product_name',
            field=models.CharField(default=1, max_length=1000),
            preserve_default=False,
        ),
    ]
